[general]
import = [
    "~/.config/alacritty/themes/themes/monokai.toml"
]

[window]
opacity = 0.9
padding.x = 5
padding.y = 5
decorations = "None"
startup_mode = "Maximized"

[font]
normal = { family = "Fira Code", style = "Regular" }
size = 11

[cursor]
style = { shape = "Block", blinking = "Always" }

[terminal]
shell = "fish"
