[general]
import = ["~/.config/alacritty/themes/themes/monokai.toml"]

[window]
opacity = 0.95
padding.x = 10
padding.y = 10
decorations = "None"
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono NF", style = "Regular" }
size = 12
offset = { x = 0, y = 7 }
glyph_offset = { x = 0, y = 7 }

[cursor]
style = { shape = "Block", blinking = "Always" }

[terminal]
shell = "fish"

[colors.primary]
background = "#222222"
