return {
  "olimorris/onedarkpro.nvim",
  opts = {
    colors = {
      line_number = "#7f848e",
    },
    highlights = {
      Comment = { italic = true },
      Directory = { bold = true },
      ErrorMsg = { italic = true, bold = true },
    },
    styles = {
      types = "NONE",
      methods = "NONE",
      numbers = "NONE",
      strings = "NONE",
      comments = "italic",
      keywords = "bold,italic",
      constants = "NONE",
      functions = "italic",
      operators = "NONE",
      variables = "NONE",
      parameters = "NONE",
      conditionals = "italic",
      virtual_text = "NONE",
    },
    options = {
      cursorline = true,
      transparency = true,
      terminal_colors = true,
      highlight_inactive_windows = false,
    },
    plugins = {
      aerial = true,
      barbar = true,
      blink_cmp = true,
      codecompanion = true,
      copilot = true,
      dashboard = true,
      flash_nvim = true,
      gitgraph_nvim = true,
      gitsigns = true,
      hop = true,
      indentline = true,
      leap = true,
      lsp_saga = true,
      lsp_semantic_tokens = true,
      marks = true,
      mini_diff = true,
      mini_icons = true,
      mini_indentscope = true,
      mini_test = true,
      neotest = true,
      neo_tree = true,
      nvim_cmp = true,
      nvim_bqf = true,
      nvim_dap = true,
      nvim_dap_ui = true,
      nvim_hlslens = true,
      nvim_lsp = true,
      nvim_navic = true,
      nvim_notify = true,
      nvim_tree = true,
      nvim_ts_rainbow = true,
      op_nvim = true,
      packer = true,
      persisted = true,
      polygot = true,
      rainbow_delimiters = true,
      render_markdown = true,
      startify = true,
      telescope = true,
      toggleterm = true,
      treesitter = true,
      trouble = true,
      vim_ultest = true,
      which_key = true,
      vim_dadbod_ui = true,
    },
  },
}
